### ISSUE TITLE
URL changed

### ISSUE THREAD

**Issue by bbaassssiiee** [dockpack/base_boost#46]
https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz.json => Forbidden

https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz.json => OK

**Comment by bbaassssiiee** [comment]
`roles/requirements.yml` should have 2.1.5:

```yaml
- src: https://github.com/dockpack/base_boost.git
  scm: git
  name: base_boost
  version: 2.1.5
```
